"""Madden ML play-calling package.

Phase 1 exports the shared schema only. Training, features, dataset,
policy, registry, and inference modules are importable stubs and are not
loaded from here, so ``import cfb_coach.madden.model`` does not pull the
optional ML stack.

This package does not call plays. ``playcaller.make_call`` is unchanged.
"""

from cfb_coach.madden.model.schema import (
    CONTRACT_VERSION,
    CSV_UNKNOWN,
    DECISION_SCHEMA_VERSION,
    FEATURE_SCHEMA_VERSION,
    LOADOUT_N,
    ML_LATENCY_BUDGET_MS,
    ML_LOW_CONFIDENCE,
    PROVISIONAL_SCHEMA_VERSION,
    PROVISIONAL_TYPES,
    RANKING_STATUSES,
    SCHEMA_RECORD_TYPES,
    AdjustmentRef,
    AppliedPlaybookRef,
    CandidatePlay,
    CandidateScore,
    CoachingDecision,
    CoachingMode,
    MLStatus,
    ExecutedStatus,
    HintSource,
    MLConfig,
    OpponentContextKey,
    PenaltyCall,
    PolicySource,
    PropensityMethod,
    PropensityOverrideReason,
    DataHash,
    DecisionStage,
    ExecutedPlay,
    FeatureValue,
    FeatureVector,
    GameState,
    GateResult,
    MetricRecord,
    ModelRegistryEntry,
    ObservedLook,
    OpponentContext,
    OpponentKind,
    OutcomeEstimates,
    PlayRanking,
    Possession,
    PreSnapObservation,
    RankedPlay,
    RecentSnap,
    RosterFeature,
    RosterSnapshot,
    SnapOutcome,
    StagePick,
    TendencyCount,
    Tri,
    Verification,
    candidate_in_book,
    from_dict,
    legal_candidates,
    pre_snap_field_names,
    to_dict,
)

__all__ = [
    "CONTRACT_VERSION",
    "CSV_UNKNOWN",
    "DECISION_SCHEMA_VERSION",
    "FEATURE_SCHEMA_VERSION",
    "LOADOUT_N",
    "ML_LATENCY_BUDGET_MS",
    "ML_LOW_CONFIDENCE",
    "PROVISIONAL_SCHEMA_VERSION",
    "PROVISIONAL_TYPES",
    "RANKING_STATUSES",
    "SCHEMA_RECORD_TYPES",
    "AdjustmentRef",
    "AppliedPlaybookRef",
    "CandidatePlay",
    "CandidateScore",
    "CoachingDecision",
    "CoachingMode",
    "MLStatus",
    "ExecutedStatus",
    "HintSource",
    "MLConfig",
    "OpponentContextKey",
    "PenaltyCall",
    "PolicySource",
    "PropensityMethod",
    "PropensityOverrideReason",
    "DataHash",
    "DecisionStage",
    "ExecutedPlay",
    "FeatureValue",
    "FeatureVector",
    "GameState",
    "GateResult",
    "MetricRecord",
    "ModelRegistryEntry",
    "ObservedLook",
    "OpponentContext",
    "OpponentKind",
    "OutcomeEstimates",
    "PlayRanking",
    "Possession",
    "PreSnapObservation",
    "RankedPlay",
    "RecentSnap",
    "RosterFeature",
    "RosterSnapshot",
    "SnapOutcome",
    "StagePick",
    "TendencyCount",
    "Tri",
    "Verification",
    "candidate_in_book",
    "from_dict",
    "legal_candidates",
    "pre_snap_field_names",
    "to_dict",
]
