"""Seeded defense picks stay put when sampling probabilities are attached."""

from __future__ import annotations

import random
import unittest

from cfb_coach.madden import defense_select as ds
from cfb_coach.madden.situation import parse_madden_situation
from tests.test_ingame_scouting_research import _d_book

# Recorded from select_defense before call_probs existed.
# Each row is seed, situation, formation, play, family. db is None.
# Random(seed) is constructed once per row.
_BEFORE = (
    (0, 'd 1&10', '4-3 Over', 'Cover 2 Man', 'man'),
    (0, 'd 2&7', '4-3 Over', 'Cover 2 Man', 'man'),
    (0, 'd 3&10', 'Dime 3-2 Odd', 'Cover 3 Lock', 'man'),
    (0, 'd 3&1', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (0, 'd 1&goal opp 5', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (0, 'd 2&5 opp 25', '4-3 Over', 'Cover 2 Man', 'man'),
    (1, 'd 1&10', 'Nickel Over', 'Cover 6', 'two_high'),
    (1, 'd 2&7', 'Nickel Over', 'Cover 6', 'two_high'),
    (1, 'd 3&10', 'Nickel Over', 'Cover 4 Drop Field', 'two_high'),
    (1, 'd 3&1', 'Nickel Double Mug', 'Tampa 2', 'cover2'),
    (1, 'd 1&goal opp 5', 'Nickel Double Mug', 'Cover 3 Sky', 'single_high'),
    (1, 'd 2&5 opp 25', 'Nickel Over', 'Cover 6', 'two_high'),
    (2, 'd 1&10', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
    (2, 'd 2&7', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
    (2, 'd 3&10', 'Dime 3-2 Odd', 'Hot Blitz 3', 'pressure'),
    (2, 'd 3&1', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
    (2, 'd 1&goal opp 5', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
    (2, 'd 2&5 opp 25', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
    (3, 'd 1&10', 'Nickel Over', 'Cover 4 Palms', 'two_high'),
    (3, 'd 2&7', 'Nickel Over', 'Cover 4 Palms', 'two_high'),
    (3, 'd 3&10', 'Dime 3-2 Odd', 'Cover 6', 'two_high'),
    (3, 'd 3&1', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (3, 'd 1&goal opp 5', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (3, 'd 2&5 opp 25', 'Nickel Over', 'Cover 4 Palms', 'two_high'),
    (4, 'd 1&10', '4-3 Over', 'Cover 4 Quarters', 'two_high'),
    (4, 'd 2&7', '4-3 Over', 'Cover 4 Quarters', 'two_high'),
    (4, 'd 3&10', 'Dime 3-2 Odd', 'Cover 4 Drop', 'two_high'),
    (4, 'd 3&1', '4-3 Over', 'Cover 3 Cloud Str', 'single_high'),
    (4, 'd 1&goal opp 5', '4-3 Over', 'Cover 3 Cloud Str', 'single_high'),
    (4, 'd 2&5 opp 25', '4-3 Over', 'Cover 4 Quarters', 'two_high'),
    (5, 'd 1&10', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (5, 'd 2&7', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (5, 'd 3&10', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (5, 'd 3&1', '4-3 Over', 'Cover 2 Man', 'man'),
    (5, 'd 1&goal opp 5', '4-3 Over', 'Cover 2 Man', 'man'),
    (5, 'd 2&5 opp 25', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (6, 'd 1&10', '4-3 Over', 'Cover 2 Man', 'man'),
    (6, 'd 2&7', '4-3 Over', 'Cover 2 Man', 'man'),
    (6, 'd 3&10', 'Dime 3-2 Odd', 'Cover 3 Lock', 'man'),
    (6, 'd 3&1', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (6, 'd 1&goal opp 5', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (6, 'd 2&5 opp 25', '4-3 Over', 'Cover 2 Man', 'man'),
    (7, 'd 1&10', '4-3 Over', 'Cover 2 Hard Flat', 'cover2'),
    (7, 'd 2&7', '4-3 Over', 'Cover 2 Hard Flat', 'cover2'),
    (7, 'd 3&10', 'Dime 3-2 Odd', 'Cover 4 Drop', 'two_high'),
    (7, 'd 3&1', '4-3 Over', 'Cover 3 Cloud Str', 'single_high'),
    (7, 'd 1&goal opp 5', '4-3 Over', '1 Hole Press', 'man'),
    (7, 'd 2&5 opp 25', '4-3 Over', 'Cover 2 Hard Flat', 'cover2'),
    (8, 'd 1&10', 'Nickel Over', 'Cover 6', 'two_high'),
    (8, 'd 2&7', 'Nickel Over', 'Cover 6', 'two_high'),
    (8, 'd 3&10', 'Nickel Over', 'Cover 4 Drop Field', 'two_high'),
    (8, 'd 3&1', 'Nickel Double Mug', 'Cover 3 Sky', 'single_high'),
    (8, 'd 1&goal opp 5', 'Nickel Double Mug', 'Cover 3 Sky', 'single_high'),
    (8, 'd 2&5 opp 25', 'Nickel Over', 'Cover 6', 'two_high'),
    (9, 'd 1&10', '4-3 Over', 'Sam Edge 3', 'single_high'),
    (9, 'd 2&7', '4-3 Over', 'Sam Edge 3', 'single_high'),
    (9, 'd 3&10', 'Nickel Double Mug', '2 Invert Hard Flat', 'cover2'),
    (9, 'd 3&1', '4-3 Over', 'Sam Edge 3', 'single_high'),
    (9, 'd 1&goal opp 5', '4-3 Over', 'Cover 1 Contain', 'man'),
    (9, 'd 2&5 opp 25', '4-3 Over', 'Sam Edge 3', 'single_high'),
    (10, 'd 1&10', '4-3 Over', 'Sam Edge 3', 'single_high'),
    (10, 'd 2&7', '4-3 Over', 'Sam Edge 3', 'single_high'),
    (10, 'd 3&10', 'Nickel Double Mug', '2 Invert Hard Flat', 'cover2'),
    (10, 'd 3&1', '4-3 Over', 'Cover 1 Contain', 'man'),
    (10, 'd 1&goal opp 5', '4-3 Over', 'Cover 1 Contain', 'man'),
    (10, 'd 2&5 opp 25', '4-3 Over', 'Sam Edge 3', 'single_high'),
    (11, 'd 1&10', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (11, 'd 2&7', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (11, 'd 3&10', 'Nickel Double Mug', 'Cover 2 Invert', 'cover2'),
    (11, 'd 3&1', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (11, 'd 1&goal opp 5', '4-3 Over', 'Cover 1 Hole', 'man'),
    (11, 'd 2&5 opp 25', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (12, 'd 1&10', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (12, 'd 2&7', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (12, 'd 3&10', 'Nickel Double Mug', 'Cover 2 Invert', 'cover2'),
    (12, 'd 3&1', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (12, 'd 1&goal opp 5', '4-3 Over', 'Cover 1 Hole', 'man'),
    (12, 'd 2&5 opp 25', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (13, 'd 1&10', 'Nickel Over', 'Cover 4 Quarters', 'two_high'),
    (13, 'd 2&7', 'Nickel Over', 'Cover 4 Quarters', 'two_high'),
    (13, 'd 3&10', 'Dime 3-2 Odd', 'Cover 6 Willie', 'two_high'),
    (13, 'd 3&1', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (13, 'd 1&goal opp 5', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (13, 'd 2&5 opp 25', 'Nickel Over', 'Cover 4 Quarters', 'two_high'),
    (14, 'd 1&10', 'Nickel Over', 'Cover 4 Quarters', 'two_high'),
    (14, 'd 2&7', 'Nickel Over', 'Cover 4 Quarters', 'two_high'),
    (14, 'd 3&10', 'Dime 3-2 Odd', 'Cover 6 Willie', 'two_high'),
    (14, 'd 3&1', 'Nickel Double Mug', 'Nickel 2 Trap', 'cover2'),
    (14, 'd 1&goal opp 5', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (14, 'd 2&5 opp 25', 'Nickel Over', 'Cover 4 Quarters', 'two_high'),
    (15, 'd 1&10', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (15, 'd 2&7', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (15, 'd 3&10', 'Dime 3-2 Odd', 'DB Fire 2', 'pressure'),
    (15, 'd 3&1', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (15, 'd 1&goal opp 5', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (15, 'd 2&5 opp 25', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (16, 'd 1&10', 'Nickel Double Mug', '2 Invert Hard Flat', 'cover2'),
    (16, 'd 2&7', 'Nickel Double Mug', '2 Invert Hard Flat', 'cover2'),
    (16, 'd 3&10', 'Nickel Double Mug', '2 Invert Hard Flat', 'cover2'),
    (16, 'd 3&1', '4-3 Over', 'Sam Edge 3', 'single_high'),
    (16, 'd 1&goal opp 5', '4-3 Over', 'Cover 1 Contain', 'man'),
    (16, 'd 2&5 opp 25', 'Nickel Double Mug', '2 Invert Hard Flat', 'cover2'),
    (17, 'd 1&10', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (17, 'd 2&7', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (17, 'd 3&10', 'Nickel Double Mug', 'Nickel 2 Trap', 'cover2'),
    (17, 'd 3&1', '4-3 Over', 'Cover 2 Man', 'man'),
    (17, 'd 1&goal opp 5', '4-3 Over', 'Cover 2 Man', 'man'),
    (17, 'd 2&5 opp 25', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (18, 'd 1&10', 'Nickel Over', 'Cover 4 Palms', 'two_high'),
    (18, 'd 2&7', 'Nickel Over', 'Cover 4 Palms', 'two_high'),
    (18, 'd 3&10', 'Dime 3-2 Odd', 'Cover 6', 'two_high'),
    (18, 'd 3&1', 'Nickel Double Mug', 'Cover 2 Invert', 'cover2'),
    (18, 'd 1&goal opp 5', 'Nickel Double Mug', 'Coffee House 3 Seam', 'single_high'),
    (18, 'd 2&5 opp 25', 'Nickel Over', 'Cover 4 Palms', 'two_high'),
    (19, 'd 1&10', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (19, 'd 2&7', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (19, 'd 3&10', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (19, 'd 3&1', '4-3 Over', 'Cover 2 Man', 'man'),
    (19, 'd 1&goal opp 5', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (19, 'd 2&5 opp 25', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (20, 'd 1&10', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (20, 'd 2&7', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (20, 'd 3&10', 'Dime 3-2 Odd', 'FS Zone Blitz', 'pressure'),
    (20, 'd 3&1', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (20, 'd 1&goal opp 5', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (20, 'd 2&5 opp 25', '4-3 Over', 'Thunder Smoke', 'pressure'),
    (21, 'd 1&10', 'Nickel Over', 'Cover 4 Quarters', 'two_high'),
    (21, 'd 2&7', 'Nickel Over', 'Cover 4 Quarters', 'two_high'),
    (21, 'd 3&10', 'Dime 3-2 Odd', 'Cover 6 Willie', 'two_high'),
    (21, 'd 3&1', 'Nickel Double Mug', 'Nickel 2 Trap', 'cover2'),
    (21, 'd 1&goal opp 5', 'Nickel Double Mug', 'Cover 3 Match', 'single_high'),
    (21, 'd 2&5 opp 25', 'Nickel Over', 'Cover 4 Quarters', 'two_high'),
    (22, 'd 1&10', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (22, 'd 2&7', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (22, 'd 3&10', 'Dime 3-2 Odd', 'DB Fire 2', 'pressure'),
    (22, 'd 3&1', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (22, 'd 1&goal opp 5', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (22, 'd 2&5 opp 25', '4-3 Over', 'DBL Safety Blitz', 'pressure'),
    (23, 'd 1&10', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
    (23, 'd 2&7', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
    (23, 'd 3&10', 'Dime 3-2 Odd', 'Hot Blitz 3', 'pressure'),
    (23, 'd 3&1', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
    (23, 'd 1&goal opp 5', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
    (23, 'd 2&5 opp 25', 'Nickel Double Mug', 'Blitz Loop 3', 'pressure'),
)


class TestDefenseSamplingUnchanged(unittest.TestCase):
    def test_picks_match_the_pre_probability_draws_and_probs_sum_to_one(self) -> None:
        book = _d_book()
        for seed, raw, formation, play, family in _BEFORE:
            sit = parse_madden_situation(raw, default_side="defense")
            pick = ds.select_defense(sit, "gavin", None, book, random.Random(seed))
            self.assertEqual((pick.formation, pick.play, pick.family), (formation, play, family))
            self.assertAlmostEqual(sum(pick.call_probs.values()), 1.0, delta=1e-9)
            self.assertIn((pick.formation, pick.play), pick.call_probs)
            self.assertGreater(pick.call_probs[(pick.formation, pick.play)], 0.0)


if __name__ == "__main__":
    unittest.main()
